import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NextTopLoader from "nextjs-toploader";

import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/home/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Erasmus Website",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pl">
            <body className={inter.className}>
                <NextTopLoader color="#00B4D8" showSpinner={false} />
                <Navbar />
                <main className="relative container mx-auto pt-24">
                    {children}
                </main>
                <Footer />
            </body>
        </html>
    );
}
